### ISSUE TITLE
En producción?

### ISSUE THREAD

**Issue by cgallegu** [clouw/transbank-oneclick#1]
Hola! Está esto en producción en algún lado? (como para pensar en usarlo tal-cual, o saber que cosas faltan para aportar).

Saludos!

**Comment by ramon-sg** [comment]
Hola, el proyecto que lo tiene implementado, sigue esperando la evaluación, desde el año pasado que no hay mucho movimiento con eso, pero la mayoría de las trabas están relacionadas con logos, simular timeout, termino y condiciones.
Hasta el momento no hay problemas, pero sigue estando en ambiente de desarrollo.
Tiene todo lo necesario para implementar el webservice de transbank (son pocos métodos), faltan tests y refactorizar, pero funciona sin agregar nada más que la lógica propia del negocio que lo implemente.
Saludos.
